<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net46</TargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DefineConstants>TRACE;DEBUG;KKS</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DefineConstants>TRACE;KKS</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="IllusionLibs.KoikatsuSunshine.UnityEngine.ImageConversionModule" Version="2019.4.9" />
		<PackageReference Include="IllusionLibs.KoikatsuSunshine.UnityEngine.TextRenderingModule" Version="2019.4.9" />
		<PackageReference Include="IllusionModdingAPI.KKSAPI" Version="1.38.0" />
	</ItemGroup>
	<PropertyGroup>
		<PostBuildEvent>IF EXIST "$(SolutionDir)PostBuild.bat" CALL "$(SolutionDir)PostBuild.bat" "$(TargetPath)" KKS</PostBuildEvent>
	</PropertyGroup>
	<Import Project="..\Core_BreastPhysicsController\Core_BreastPhysicsController.projitems" Label="Shared" />
</Project>